# -*- coding: utf-8 -*-
"""Chatbot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dhd2VgrppwZG0fcWlYYuAhW1ShLDi7Av
"""

import random

responses = {
    "hello": ["Hi there!", "Hello!", "Hey!"],
    "how are you": ["I'm doing well, thank you.", "Not too bad, thanks for asking.", "I'm just fine."],
    "what's your name": ["My name is Chatbot.", "I go by Chatbot.", "You can call me Chatbot."],
    "default": ["I'm sorry, I didn't understand what you said.", "Can you please rephrase that?", "I'm not sure what you mean."],
}

def get_response(user_input):
    user_input = user_input.lower().strip()
   
    if user_input in responses:
        return random.choice(responses[user_input])
    else:
        return random.choice(responses["default"])


def run_chatbot():
    print("Hi, I'm Chatbot. How can I help you today?")
   
    while True:
        user_input = input("You: ")
       
        bot_response = get_response(user_input)
       
        print("Chatbot: " + bot_response)
       
        if user_input.lower().strip() == "bye":
            print("Chatbot: Goodbye!")
            break

run_chatbot()